"""increment - A/B testing querying and stats engine."""

import importlib
from importlib.metadata import PackageNotFoundError, version
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from increment._study import ParallelStudyEnvelope, StudyEnvelope, SwitchbackStudyEnvelope
    from increment.absorption import absorb_factor
    from increment.analysis import Analysis, fit_predeclared_adjustment
    from increment.breakout.heterogeneity import segment_contrast, segment_heterogeneity
    from increment.breakout.projection import to_frame
    from increment.breakout.rollout import segment_rollout_recommendation
    from increment.cate import estimate_cate, select_targeting_rule, targeting_rule, validate_cate
    from increment.errors import (
        CapabilityError,
        CodedError,
        DefinitionError,
        IncrementDeprecationWarning,
        IncrementRuntimeWarning,
        IncrementWarning,
        InvalidRequestError,
        RefusalSpec,
        UnsupportedRequestError,
        WarningSpec,
        WireFormatError,
        refuse,
        warn,
    )
    from increment.estimation._adjust.overlap import IdentificationError
    from increment.estimation.armstats import SummaryStats
    from increment.estimation.cate import Covariate
    from increment.estimation.decision_types import AsymptoticSequentialEvidence
    from increment.estimation.diagnostics import allocation_posterior_bands, sample_ratio_mismatch
    from increment.estimation.engine import Method
    from increment.estimation.inference import Normal
    from increment.estimation.sequential import (
        AlwaysValid,
        AsymptoticMean,
    )
    from increment.estimation.sequential_result import AsymptoticSequentialResult
    from increment.estimation.sequential_runtime import estimate_sequential
    from increment.estimation.targeting import ClusterBootstrap
    from increment.frame import MetricSpec
    from increment.logged_policy import (
        LoggedTrace,
        PolicyRegistry,
        TabularPolicy,
        estimate_policy_contrast,
    )
    from increment.power import (
        Baseline,
        PowerDesign,
        SwitchbackBaseline,
        achieved_power,
        minimum_detectable_effect,
        power_curve,
        required_sample_size,
        switchback_achieved_power,
        switchback_minimum_detectable_effect,
        switchback_required_blocks_or_units,
        unit_cycle_power_lower_bound,
    )
    from increment.query.artifact_contract import (
        ArtifactPublication,
        ArtifactSnapshot,
        ArtifactStore,
        compile_unit_day_artifact_context,
        unit_day_artifact_extension_catalog,
    )
    from increment.query.artifact_digest import (
        DigestType,
        FieldSpec,
        RelationDigests,
        canonical_json_bytes,
        canonical_row_bytes,
        canonical_rows_bytes,
        canonical_schema_bytes,
        content_sha256,
        context_sha256,
        digest_relation,
        extension_definition_sha256,
        extension_source_provenance_sha256,
        manifest_sha256,
        request_sha256,
        schema_sha256,
    )
    from increment.query.session import SourceSnapshotEvidence
    from increment.reporting import Report
    from increment.semantics.artifact import (
        ArtifactContext,
        ArtifactExtensionCatalogEntry,
        ArtifactExtensionRef,
        ArtifactExtensionRequest,
        ArtifactRelationRef,
        AssignmentCountsExtension,
        AssignmentCountsRequest,
        BaseRelations,
        BreakoutDimensionExtension,
        BreakoutDimensionRequest,
        ClusterIdentityExtension,
        ClusterIdentityRequest,
        CupedPreperiodExtension,
        CupedPreperiodRequest,
        EncouragementUptakeExtension,
        EncouragementUptakeRequest,
        ExtensionRefBase,
        ExtensionRequestBase,
        FactorDimensionExtension,
        FactorDimensionRequest,
        Freshness,
        MeasureManifest,
        MetricMeasure,
        RatioMetricMeasure,
        RelationLocator,
        RelationRole,
        SimpleMetricMeasure,
        SiteVolumeExtension,
        SiteVolumeRequest,
        TriggerMeasureStatsExtension,
        TriggerMeasureStatsRequest,
        TriggerPopulationExtension,
        TriggerPopulationRequest,
        UnitCovariateExtension,
        UnitCovariateLevelExtension,
        UnitCovariateLevelRequest,
        UnitCovariateRequest,
        UnitDayArtifactManifest,
        UnitDayArtifactRef,
    )
    from increment.semantics.assignment import (
        Assignment,
        IndependentBernoulliOrder,
        ParallelAssignment,
        SharedScheduleOrder,
        SwitchbackAssignment,
        SwitchbackWindow,
    )
    from increment.semantics.design import (
        AdjustmentSet,
        Design,
        Encouragement,
        ExclusionRestriction,
        IdentificationGate,
        Observational,
        Randomized,
        UptakeSpec,
    )
    from increment.semantics.models import (
        AnalysisPlan,
        Definitions,
        ExperimentMetric,
        InferenceSpec,
        Metric,
        MultiplicitySpec,
        Winsorization,
    )
    from increment.semantics.sequential import (
        JointReveal,
        PredeclaredAdjustment,
        PredictivePrior,
        ScalarMeanModel,
        SequentialCell,
        SequentialCompliancePolicy,
        SequentialModel,
        SequentialRegistration,
    )
    from increment.semantics.unit_cycle import (
        ProspectiveAssumptionProvenance,
        UnitCycleReference,
        UnitCycleTApproximation,
        UnitCycleVarianceEnvelope,
    )
    from increment.sequential_source import sequential_definition_id
    from increment.sequential_state import (
        SequentialSnapshot,
        capture_sequential_snapshot,
        declare_sequential_freeze,
        snapshot_from_json,
    )

try:
    __version__ = version("increment")
except PackageNotFoundError:  # pragma: no cover - source tree without an install
    __version__ = "0.0.0.dev0"

__all__ = [
    "Analysis",
    "Report",
    "Definitions",
    "Metric",
    "MetricSpec",
    "Winsorization",
    "Design",
    "Randomized",
    "Observational",
    "Encouragement",
    "RelationLocator",
    "RelationRole",
    "UnitDayArtifactRef",
    "ArtifactRelationRef",
    "BaseRelations",
    "Freshness",
    "MeasureManifest",
    "SimpleMetricMeasure",
    "RatioMetricMeasure",
    "MetricMeasure",
    "ArtifactContext",
    "UnitDayArtifactManifest",
    "ExtensionRefBase",
    "BreakoutDimensionExtension",
    "FactorDimensionExtension",
    "ClusterIdentityExtension",
    "CupedPreperiodExtension",
    "AssignmentCountsExtension",
    "TriggerPopulationExtension",
    "TriggerMeasureStatsExtension",
    "EncouragementUptakeExtension",
    "SiteVolumeExtension",
    "UnitCovariateExtension",
    "UnitCovariateLevelExtension",
    "ArtifactDigestError",
    "DigestType",
    "FieldSpec",
    "RelationDigests",
    "canonical_schema_bytes",
    "canonical_row_bytes",
    "canonical_rows_bytes",
    "canonical_json_bytes",
    "schema_sha256",
    "content_sha256",
    "digest_relation",
    "manifest_sha256",
    "context_sha256",
    "request_sha256",
    "extension_definition_sha256",
    "extension_source_provenance_sha256",
    "ArtifactExtensionRef",
    "ExtensionRequestBase",
    "BreakoutDimensionRequest",
    "FactorDimensionRequest",
    "ClusterIdentityRequest",
    "CupedPreperiodRequest",
    "AssignmentCountsRequest",
    "TriggerPopulationRequest",
    "TriggerMeasureStatsRequest",
    "EncouragementUptakeRequest",
    "SiteVolumeRequest",
    "UnitCovariateRequest",
    "UnitCovariateLevelRequest",
    "ArtifactExtensionRequest",
    "ArtifactExtensionCatalogEntry",
    "ArtifactPublication",
    "ArtifactSnapshot",
    "ArtifactStore",
    "compile_unit_day_artifact_context",
    "unit_day_artifact_extension_catalog",
    "UptakeSpec",
    "ExclusionRestriction",
    "AdjustmentSet",
    "IdentificationGate",
    "AnalysisPlan",
    "MultiplicitySpec",
    "ExperimentMetric",
    "InferenceSpec",
    "Method",
    "Normal",
    "AsymptoticMean",
    "AsymptoticSequentialResult",
    "AsymptoticSequentialEvidence",
    "ScalarMeanModel",
    "PredeclaredAdjustment",
    "fit_predeclared_adjustment",
    "AlwaysValid",
    "PredictivePrior",
    "SequentialModel",
    "JointReveal",
    "SequentialCell",
    "SequentialRegistration",
    "SequentialCompliancePolicy",
    "SequentialSnapshot",
    "capture_sequential_snapshot",
    "declare_sequential_freeze",
    "snapshot_from_json",
    "estimate_sequential",
    "sequential_definition_id",
    "Covariate",
    "ClusterBootstrap",
    "SummaryStats",
    "SwitchbackBaseline",
    "ProspectiveAssumptionProvenance",
    "UnitCycleVarianceEnvelope",
    "UnitCycleTApproximation",
    "UnitCycleReference",
    "switchback_achieved_power",
    "switchback_minimum_detectable_effect",
    "switchback_required_blocks_or_units",
    "unit_cycle_power_lower_bound",
    "Baseline",
    "PowerDesign",
    "required_sample_size",
    "achieved_power",
    "minimum_detectable_effect",
    "power_curve",
    "sample_ratio_mismatch",
    "allocation_posterior_bands",
    "absorb_factor",
    "estimate_cate",
    "validate_cate",
    "select_targeting_rule",
    "targeting_rule",
    "segment_heterogeneity",
    "segment_contrast",
    "segment_rollout_recommendation",
    "estimate_policy_contrast",
    "LoggedTrace",
    "PolicyRegistry",
    "TabularPolicy",
    "to_frame",
    "impute",
    "IdentificationError",
    "CapabilityError",
    "CodedError",
    "DefinitionError",
    "IncrementDeprecationWarning",
    "IncrementRuntimeWarning",
    "IncrementWarning",
    "InvalidRequestError",
    "RefusalSpec",
    "UnsupportedRequestError",
    "WarningSpec",
    "WireFormatError",
    "refuse",
    "warn",
    "__version__",
    "Assignment",
    "ParallelAssignment",
    "IndependentBernoulliOrder",
    "SharedScheduleOrder",
    "SwitchbackWindow",
    "SwitchbackAssignment",
    "ParallelStudyEnvelope",
    "SwitchbackStudyEnvelope",
    "StudyEnvelope",
    "SourceSnapshotEvidence",
]

_LAZY_IMPORTS = {
    # Submodule, not an attribute of one: __getattr__ returns the module
    # itself when the attr slot is None.
    "impute": ("increment.impute", None),
    "Report": ("increment.reporting", "Report"),
    "Analysis": ("increment.analysis", "Analysis"),
    "SourceSnapshotEvidence": ("increment.query.session", "SourceSnapshotEvidence"),
    "MetricSpec": ("increment.frame", "MetricSpec"),
    # The identification union every readout's `design=` argument names.
    # Annotation-only: construct one of its members, which are exported
    # alongside it.
    "Design": ("increment.semantics.design", "Design"),
    "Randomized": ("increment.semantics.design", "Randomized"),
    "Observational": ("increment.semantics.design", "Observational"),
    "Encouragement": ("increment.semantics.design", "Encouragement"),
    "UptakeSpec": ("increment.semantics.design", "UptakeSpec"),
    "ExclusionRestriction": ("increment.semantics.design", "ExclusionRestriction"),
    "AdjustmentSet": ("increment.semantics.design", "AdjustmentSet"),
    "IdentificationGate": ("increment.semantics.design", "IdentificationGate"),
    "IdentificationError": ("increment.estimation._adjust.overlap", "IdentificationError"),
    "CapabilityError": ("increment.errors", "CapabilityError"),
    "CodedError": ("increment.errors", "CodedError"),
    "DefinitionError": ("increment.errors", "DefinitionError"),
    "IncrementDeprecationWarning": ("increment.errors", "IncrementDeprecationWarning"),
    "IncrementRuntimeWarning": ("increment.errors", "IncrementRuntimeWarning"),
    "IncrementWarning": ("increment.errors", "IncrementWarning"),
    "InvalidRequestError": ("increment.errors", "InvalidRequestError"),
    "RefusalSpec": ("increment.errors", "RefusalSpec"),
    "UnsupportedRequestError": ("increment.errors", "UnsupportedRequestError"),
    "WarningSpec": ("increment.errors", "WarningSpec"),
    "WireFormatError": ("increment.errors", "WireFormatError"),
    "refuse": ("increment.errors", "refuse"),
    "warn": ("increment.errors", "warn"),
    "absorb_factor": ("increment.absorption", "absorb_factor"),
    "estimate_cate": ("increment.cate", "estimate_cate"),
    "validate_cate": ("increment.cate", "validate_cate"),
    "Covariate": ("increment.estimation.cate", "Covariate"),
    "ClusterBootstrap": ("increment.estimation.targeting", "ClusterBootstrap"),
    "targeting_rule": ("increment.cate", "targeting_rule"),
    "select_targeting_rule": ("increment.cate", "select_targeting_rule"),
    "SummaryStats": ("increment.estimation.armstats", "SummaryStats"),
    "Method": ("increment.estimation.engine", "Method"),
    "AsymptoticMean": ("increment.estimation.sequential", "AsymptoticMean"),
    "AsymptoticSequentialResult": (
        "increment.estimation.sequential_result",
        "AsymptoticSequentialResult",
    ),
    "AsymptoticSequentialEvidence": (
        "increment.estimation.decision_types",
        "AsymptoticSequentialEvidence",
    ),
    "ScalarMeanModel": ("increment.semantics.sequential", "ScalarMeanModel"),
    "PredeclaredAdjustment": ("increment.semantics.sequential", "PredeclaredAdjustment"),
    "fit_predeclared_adjustment": ("increment.analysis", "fit_predeclared_adjustment"),
    "AlwaysValid": ("increment.estimation.sequential", "AlwaysValid"),
    "PredictivePrior": ("increment.semantics.sequential", "PredictivePrior"),
    "SequentialModel": ("increment.semantics.sequential", "SequentialModel"),
    "JointReveal": ("increment.semantics.sequential", "JointReveal"),
    "SequentialCell": ("increment.semantics.sequential", "SequentialCell"),
    "SequentialRegistration": ("increment.semantics.sequential", "SequentialRegistration"),
    "SequentialCompliancePolicy": ("increment.semantics.sequential", "SequentialCompliancePolicy"),
    "SequentialSnapshot": ("increment.sequential_state", "SequentialSnapshot"),
    "capture_sequential_snapshot": ("increment.sequential_state", "capture_sequential_snapshot"),
    "declare_sequential_freeze": ("increment.sequential_state", "declare_sequential_freeze"),
    "snapshot_from_json": ("increment.sequential_state", "snapshot_from_json"),
    "estimate_sequential": ("increment.estimation.sequential_runtime", "estimate_sequential"),
    "sequential_definition_id": ("increment.sequential_source", "sequential_definition_id"),
    "to_frame": ("increment.breakout.projection", "to_frame"),
    "segment_heterogeneity": ("increment.breakout.heterogeneity", "segment_heterogeneity"),
    "segment_contrast": ("increment.breakout.heterogeneity", "segment_contrast"),
    "segment_rollout_recommendation": (
        "increment.breakout.rollout",
        "segment_rollout_recommendation",
    ),
    "estimate_policy_contrast": ("increment.logged_policy", "estimate_policy_contrast"),
    "LoggedTrace": ("increment.logged_policy", "LoggedTrace"),
    "PolicyRegistry": ("increment.logged_policy", "PolicyRegistry"),
    "TabularPolicy": ("increment.logged_policy", "TabularPolicy"),
    "SwitchbackBaseline": ("increment.power", "SwitchbackBaseline"),
    "ProspectiveAssumptionProvenance": (
        "increment.semantics.unit_cycle",
        "ProspectiveAssumptionProvenance",
    ),
    "UnitCycleVarianceEnvelope": ("increment.semantics.unit_cycle", "UnitCycleVarianceEnvelope"),
    "UnitCycleTApproximation": ("increment.semantics.unit_cycle", "UnitCycleTApproximation"),
    "UnitCycleReference": ("increment.semantics.unit_cycle", "UnitCycleReference"),
    "switchback_achieved_power": ("increment.power", "switchback_achieved_power"),
    "switchback_minimum_detectable_effect": (
        "increment.power",
        "switchback_minimum_detectable_effect",
    ),
    "switchback_required_blocks_or_units": (
        "increment.power",
        "switchback_required_blocks_or_units",
    ),
    "unit_cycle_power_lower_bound": ("increment.power", "unit_cycle_power_lower_bound"),
    "Baseline": ("increment.power", "Baseline"),
    "PowerDesign": ("increment.power", "PowerDesign"),
    "power_curve": ("increment.power", "power_curve"),
    "achieved_power": ("increment.power", "achieved_power"),
    "minimum_detectable_effect": ("increment.power", "minimum_detectable_effect"),
    "required_sample_size": ("increment.power", "required_sample_size"),
    "Definitions": ("increment.semantics.models", "Definitions"),
    "ExperimentMetric": ("increment.semantics.models", "ExperimentMetric"),
    "Normal": ("increment.estimation.inference", "Normal"),
    "Metric": ("increment.semantics.models", "Metric"),
    "Winsorization": ("increment.semantics.models", "Winsorization"),
    "AnalysisPlan": ("increment.semantics.models", "AnalysisPlan"),
    "MultiplicitySpec": ("increment.semantics.models", "MultiplicitySpec"),
    "InferenceSpec": ("increment.semantics.models", "InferenceSpec"),
    "sample_ratio_mismatch": ("increment.estimation.diagnostics", "sample_ratio_mismatch"),
    "allocation_posterior_bands": (
        "increment.estimation.diagnostics",
        "allocation_posterior_bands",
    ),
    "Assignment": ("increment.semantics.assignment", "Assignment"),
    "ParallelAssignment": ("increment.semantics.assignment", "ParallelAssignment"),
    "IndependentBernoulliOrder": (
        "increment.semantics.assignment",
        "IndependentBernoulliOrder",
    ),
    "SharedScheduleOrder": ("increment.semantics.assignment", "SharedScheduleOrder"),
    "SwitchbackWindow": ("increment.semantics.assignment", "SwitchbackWindow"),
    "SwitchbackAssignment": ("increment.semantics.assignment", "SwitchbackAssignment"),
    "ParallelStudyEnvelope": ("increment._study", "ParallelStudyEnvelope"),
    "SwitchbackStudyEnvelope": ("increment._study", "SwitchbackStudyEnvelope"),
    "StudyEnvelope": ("increment._study", "StudyEnvelope"),
    "RelationLocator": ("increment.semantics.artifact", "RelationLocator"),
    "RelationRole": ("increment.semantics.artifact", "RelationRole"),
    "UnitDayArtifactRef": ("increment.semantics.artifact", "UnitDayArtifactRef"),
    "ArtifactRelationRef": ("increment.semantics.artifact", "ArtifactRelationRef"),
    "BaseRelations": ("increment.semantics.artifact", "BaseRelations"),
    "Freshness": ("increment.semantics.artifact", "Freshness"),
    "MeasureManifest": ("increment.semantics.artifact", "MeasureManifest"),
    "SimpleMetricMeasure": ("increment.semantics.artifact", "SimpleMetricMeasure"),
    "RatioMetricMeasure": ("increment.semantics.artifact", "RatioMetricMeasure"),
    "MetricMeasure": ("increment.semantics.artifact", "MetricMeasure"),
    "ArtifactContext": ("increment.semantics.artifact", "ArtifactContext"),
    "UnitDayArtifactManifest": ("increment.semantics.artifact", "UnitDayArtifactManifest"),
    "ExtensionRefBase": ("increment.semantics.artifact", "ExtensionRefBase"),
    "BreakoutDimensionExtension": (
        "increment.semantics.artifact",
        "BreakoutDimensionExtension",
    ),
    "FactorDimensionExtension": ("increment.semantics.artifact", "FactorDimensionExtension"),
    "ClusterIdentityExtension": ("increment.semantics.artifact", "ClusterIdentityExtension"),
    "CupedPreperiodExtension": ("increment.semantics.artifact", "CupedPreperiodExtension"),
    "AssignmentCountsExtension": ("increment.semantics.artifact", "AssignmentCountsExtension"),
    "TriggerPopulationExtension": ("increment.semantics.artifact", "TriggerPopulationExtension"),
    "TriggerMeasureStatsExtension": (
        "increment.semantics.artifact",
        "TriggerMeasureStatsExtension",
    ),
    "EncouragementUptakeExtension": (
        "increment.semantics.artifact",
        "EncouragementUptakeExtension",
    ),
    "SiteVolumeExtension": ("increment.semantics.artifact", "SiteVolumeExtension"),
    "ArtifactExtensionRef": ("increment.semantics.artifact", "ArtifactExtensionRef"),
    "ExtensionRequestBase": ("increment.semantics.artifact", "ExtensionRequestBase"),
    "BreakoutDimensionRequest": ("increment.semantics.artifact", "BreakoutDimensionRequest"),
    "FactorDimensionRequest": ("increment.semantics.artifact", "FactorDimensionRequest"),
    "ClusterIdentityRequest": ("increment.semantics.artifact", "ClusterIdentityRequest"),
    "CupedPreperiodRequest": ("increment.semantics.artifact", "CupedPreperiodRequest"),
    "AssignmentCountsRequest": ("increment.semantics.artifact", "AssignmentCountsRequest"),
    "TriggerPopulationRequest": ("increment.semantics.artifact", "TriggerPopulationRequest"),
    "TriggerMeasureStatsRequest": ("increment.semantics.artifact", "TriggerMeasureStatsRequest"),
    "EncouragementUptakeRequest": (
        "increment.semantics.artifact",
        "EncouragementUptakeRequest",
    ),
    "SiteVolumeRequest": ("increment.semantics.artifact", "SiteVolumeRequest"),
    "UnitCovariateExtension": ("increment.semantics.artifact", "UnitCovariateExtension"),
    "UnitCovariateLevelExtension": (
        "increment.semantics.artifact",
        "UnitCovariateLevelExtension",
    ),
    "UnitCovariateRequest": ("increment.semantics.artifact", "UnitCovariateRequest"),
    "UnitCovariateLevelRequest": ("increment.semantics.artifact", "UnitCovariateLevelRequest"),
    "ArtifactExtensionRequest": ("increment.semantics.artifact", "ArtifactExtensionRequest"),
    "ArtifactExtensionCatalogEntry": (
        "increment.semantics.artifact",
        "ArtifactExtensionCatalogEntry",
    ),
    "ArtifactPublication": ("increment.query.artifact_contract", "ArtifactPublication"),
    "ArtifactSnapshot": ("increment.query.artifact_contract", "ArtifactSnapshot"),
    "ArtifactStore": ("increment.query.artifact_contract", "ArtifactStore"),
    "compile_unit_day_artifact_context": (
        "increment.query.artifact_contract",
        "compile_unit_day_artifact_context",
    ),
    "unit_day_artifact_extension_catalog": (
        "increment.query.artifact_contract",
        "unit_day_artifact_extension_catalog",
    ),
    "ArtifactDigestError": ("increment.query.artifact_digest", "ArtifactDigestError"),
    "DigestType": ("increment.query.artifact_digest", "DigestType"),
    "FieldSpec": ("increment.query.artifact_digest", "FieldSpec"),
    "RelationDigests": ("increment.query.artifact_digest", "RelationDigests"),
    "canonical_schema_bytes": ("increment.query.artifact_digest", "canonical_schema_bytes"),
    "canonical_row_bytes": ("increment.query.artifact_digest", "canonical_row_bytes"),
    "canonical_rows_bytes": ("increment.query.artifact_digest", "canonical_rows_bytes"),
    "canonical_json_bytes": (
        "increment.query.artifact_digest",
        "canonical_json_bytes",
    ),
    "schema_sha256": ("increment.query.artifact_digest", "schema_sha256"),
    "content_sha256": ("increment.query.artifact_digest", "content_sha256"),
    "digest_relation": ("increment.query.artifact_digest", "digest_relation"),
    "manifest_sha256": ("increment.query.artifact_digest", "manifest_sha256"),
    "context_sha256": ("increment.query.artifact_digest", "context_sha256"),
    "request_sha256": ("increment.query.artifact_digest", "request_sha256"),
    "extension_definition_sha256": (
        "increment.query.artifact_digest",
        "extension_definition_sha256",
    ),
    "extension_source_provenance_sha256": (
        "increment.query.artifact_digest",
        "extension_source_provenance_sha256",
    ),
}


def __getattr__(name: str):
    try:
        module_name, attr_name = _LAZY_IMPORTS[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    module = importlib.import_module(module_name)
    value = module if attr_name is None else getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
